---
kind: pipeline
type: docker
name: create-docker-images

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: thegeeklab/drone-docker-buildx:23
    privileged: true
    settings:
      dockerfile: Dockerfile
#      dry_run: true
      username: 
        from_secret: docker_username
      password: 
        from_secret: docker_password
      repo: andrey0001/wireguard-client-with-ssh
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    when:
      branch:
      - master
      event:
      - promote

node:
  instance: mini
  type: docker
  
