---
kind: pipeline
type: docker
name: create-docker-images

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: thegeeklab/drone-docker-buildx:24
    privileged: true
    settings:
      dockerfile: Dockerfile
#      dry_run: true
      username: 
        from_secret: vbdocker_username
      password: 
        from_secret: vbdocker_password
      repo: viberadmin/wireguard-client-with-ssh
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    when:
      branch:
      - master
      event:
      - promote

node:
  instance: x114
  type: docker
  
  
